### ISSUE TITLE
Play sound effect (bell) before and after break

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/sane-break#10]
See also #3

This feature can be handy when using a computer at home. During the break, the user may switch to other tasks and leave. A bell informs the user, who might in another room, that the break has ended, and they can go back to use the computer.

This feature requires:
- [x] Creating bells. I choose to use LMMS to avoid copy right issues
- [x] Qt Multimedia lib is required to build, which may increase binary size

**Comment by AllanChain** [comment]
Play sound before break can also be helpful. For example, the user is using a smartphone or writing on paper and is unaware of breaks.

**Comment by wolftune** [comment]
ideally, this should be customizable, let user choose their own sounds if they like

**Comment by AllanChain** [comment]
> ideally, this should be customizable, let user choose their own sounds if they like

With the current version (https://github.com/AllanChain/sane-break/commit/4e9d70c893cc1dfc47231684f0003b8265358500), users can already choose the sound or even use local sound files.
