### ISSUE TITLE
minor bug: full-screen missing a left-side chunk

### ISSUE THREAD

**Issue by wolftune** [AllanChain/sane-break#19]
![PXL_20241120_185508113](https://github.com/user-attachments/assets/52b07898-919e-41aa-8730-9ffe854aafe9)

I have a dual-monitor setup. The full-screen view is complete on my secondary display. The primary display, a small sliver near my vertical plasma panel on the left is not covered.

I don't actually care at all, it doesn't matter for the functioning of the program, but I decided to report it as a bug anyway.

**Comment by AllanChain** [comment]
Previously, our windows reserves space for taskbars on Wayland. Therefore, when placing a window in the "top center", KDE actually places the window at the center of the remaining region. To fix this, we just tell Wayland that we don't want to reserve space for taskbars.
