### ISSUE TITLE
Portable support

### ISSUE THREAD

**Issue by vevycl** [AllanChain/sane-break#2]
Hi and thanks for the app.

I wish the app supports portable mode where it reads and writes settings to a file/directory next to the executable itself. This way it can be run from USB, for example.

A good way to do it for the app to see its path. If not in `Program Files`, then act portable.

**Comment by AllanChain** [comment]
Thanks for raising this issue. From my understanding, we can do something like this: if there is a settings file in the same directory as the app executable, then pick that setting; if not, use default locations for the settings file. Please let me know if this alternative approach can solve your problem.

**Comment by vevycl** [comment]
That can work too. Thanks.

**Comment by AllanChain** [comment]
https://github.com/AllanChain/sane-break/releases/tag/v0.4.0 is released which includes this feature.
