### ISSUE TITLE
compilation error (Ubuntu 24.04)

### ISSUE THREAD

**Issue by wolftune** [AllanChain/sane-break#4]
I'm actually using KDE Neon user edition (built on Ubuntu 24.04)

And I'm getting this error trying to build:

```
$ cmake ..
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a package configuration file provided by "QT" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "QT" to CMAKE_PREFIX_PATH or set "QT_DIR" to
  a directory containing one of the above files.  If "QT" provides a separate
  development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

```

**Comment by AllanChain** [comment]
I should have made the installation process simple and clear on Linux. Right now, with KDE Neon, some packages should be installed for compilation:
```
apt install qt6-wayland-dev liblayershellqtinterface-dev
```

**Comment by wolftune** [comment]
That worked, though it only built for Wayland.

I suggest updating the README instructions with those dependencies and mention the ones needed for x11

(personally, I might move to Wayland if Sane-break works for me, but working either way is still ideal)

**Comment by AllanChain** [comment]
`libxss-dev` is required to build for X11. I have documented the required packages [in README](https://github.com/AllanChain/sane-break?tab=readme-ov-file#compiling-from-source).
