### ISSUE TITLE
"pause when idle for" vs "pause on idle for"

### ISSUE THREAD

**Issue by wolftune** [AllanChain/sane-break#6]
"pause on idle for [time]" sounds like as soon as idle is detected, it will pause, but only for some time

I *think* the meaning is supposed to be "pause when idle for [time]", as in how much idle time is needed before a pause is activated, and the pause will go indefinitely until activity is detected

right?

If so, change "on" to "when" in prefs window

Or if I'm wrong, I guess I'm confused about why

**Comment by AllanChain** [comment]
> I think the meaning is supposed to be "pause when idle for [time]", as in how much idle time is needed before a pause is activated, and the pause will go indefinitely until activity is detected

Yes, you are right. Sorry for my poor English. I'm always confused about prepositions.

**Comment by wolftune** [comment]
I don't sense poor English as much as this is a complex case. How to make a clear idea very short… not easy

Another option: "pause after idle for"

I think that might be the clearest option here
