### ISSUE TITLE
Pause when particular programs are running

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/sane-break#9]
See also #3 

It is often the case that we want to stop the break reminder when in a video conference. Sometimes people want to stop break reminder when watching videos. In any of the cases, being able to pause for particular programs can be an important feature.

Getting a list of running programs can be achieved with shell commands on all the platforms. We have to use platform-specific ways to get the list of running programs. Besides, we may need a nice UI for configuring programs, but we can first get a simple text box to work.

**Edited**: Split full-screen window detection to a separate issue: #21

**Comment by wolftune** [comment]
note this was hinted at in the TODO list at bottom of README. Could keep that note there or not.
